name: Build And Push Docker Image

on:
  push:
    branches: ["dev"]

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Docker
        uses: docker/metadata-action@v4
        id: meta
        with:
          tags: latest
          images: ${{ secrets.DOCKERHUB_REPOSITORY }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get date
        id: date
        run: echo now=$(TZ=Asia/Shanghai date +"%Y-%m-%d %H:%M:%S") >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: now=${{ steps.date.outputs.now }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
